# Generated by Django 5.2.12 on 2026-04-07 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cor_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, default=0, null=True)),
                ('preço', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('acessorios', models.ManyToManyField(to='core.acessorio')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cor')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.modelo')),
            ],
        ),
    ]
